---
- name: Install Nginx
  yum: name=nginx state=present update_cache=true
  notify:
   - start nginx

# - name: Copy nginx configuration for wordpress
#   template: src=default.conf dest=/etc/nginx/conf.d/default.conf
#   notify: restart nginx

- name: NGINX | NGINX nginx.conf
  template:
    src=nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    backup=yes
    owner=root
    group=root
    mode=0644
  become: yes

- name: NGINX | NGINX Check nginx root directory
  stat:
    path: "{{ item }}"
  with_items: "{{ nginx_root }}"
  register: nginx_root_directory

- name: NGINX | NGINX Show message if nginx root directory existed
  debug:
    msg: 'Nginx root directory existed'
  when: nginx_root_directory.stat.exists

- name: NGINX | NGINX Create directory if not exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    group: nginx
    owner: nginx
    with_items: "{{ nginx_root }}"

- name: NGINX | restart nginx
  raw: service nginx restart
  become: yes