---
- name: Add Nginx Repository
  apt_repository: repo='ppa:nginx/stable' state=present
  register: nginxppastable

- name: Install Nginx
  apt: name=nginx state=present update_cache=true
  when: nginxppastable|success
  register: nginxinstalled
  notify:
   - start nginx

# - name: Copy nginx configuration for wordpress
#   template: src=default.conf dest=/etc/nginx/conf.d/default.conf
#   notify: restart nginx
