---
- name: Provision LEMP and related tools
  hosts: web
  gather_facts: no
  remote_user: ec2-user
  become: yes
  become_user: root
  become_method: sudo

  roles:
     - update
     - common
     - nginx
     - php
#     - mysql
     - initapps
     - restartsvcs
