---
- name: Provision LEMP and related tools
  hosts: web
  gather_facts: True
  remote_user: ec2-user
  become: yes
  become_user: root
  become_method: sudo

  roles:
     - update
     - common
     - nginx
     - php
     - restartsvcs
