---
- name: Provision LEMP and related tools
  hosts: web
  #user: root
  # remote_user: user
  sudo: yes
  gather_facts: yes

  roles:
     - update
     - common
     - nginx
     - php
     - restartsvcs
