---
- name: Provision LEMP and related tools
  hosts: web
  user: root
  remote_user: ec2-user
  gather_facts: true
  become: yes

  roles:
     - update
     - common
     - nginx
     - php
     - restartsvcs
