
---
- name: install python
  raw: sudo yum -y install python

- name: yum | yum update
  yum:
    name: "*"
    state: present
    update_cache: yes
  become: yes

- name: yum | ensure core packages are installed
  yum:
    name:
      [
        'curl',
        'git',
        'make',
        'tree',
        'unzip',
        'telnet'
      ]
    state: present
  become: yes

- name: Upgrade Server
  yum:
    name: "*"
    state: latest
  become: yes