
---
- name: install python2
  raw: sudo yum -y install python

- name: yum | yum update
  yum:
    name: "*"
    state: present
    update_cache: yes
  sudo: true

- name: yum | ensure core packages are installed
  yum:
    name: "{{ item }}"
    state: present
  sudo: true
  with_items:
    - curl
    - git
    - make
    - python-software-properties
    - supervisor
    - tree
    - unzip

- name: Upgrade Server
  yum:
    name: "*"
    state: latest