---
- name: PHP | Add php-7.3 PPA
  yum: name=epel-release state=present
  become: yes

- name: PHP | install php packages
  yum:
    name:
      [
        'php-fpm',
        'php-cli',
        'php-common',
        'php-curl',
        'php-json',
        'php-gd',
        # 'php73-mcrypt',
        'php-odbc',
        'php-pgsql',
        'php-mbstring',
        'php-mysqlnd',
        'php-xmlrpc',
        'php-opcache',
        'php-intl',
        'php-bz2',
        'php-xml'
      ]
    state: installed
  become: yes

- name: PHP | FPM www.conf
  template:
    src=www.conf.j2
    dest=/etc/php-fpm.d/www.conf
    backup=yes
    owner=root
    group=root
    mode=0644
  become: yes

- name: PHP | CLI php.ini
  template:
    src=php.ini.j2
    dest=/etc/php.ini
    backup=yes
    owner=root
    group=root
    mode=0644
  become: yes

- name: PHP | UPSTREAM php-fpm.conf
  template:
    src=php-fpm.conf.j2
    dest=/etc/nginx/conf.d/php-fpm.conf
    backup=yes
    owner=root
    group=root
    mode=0644
  become: yes

- name: PHP | restart nginx
  raw: service nginx restart
  become: yes

- name: PHP | restart fpm
  raw: service php-fpm restart
  become: yes
